#!/bin/sh -eu
# Smart askpass that returns different values based on the prompt
case "$1" in
    *Password*)
        echo "foobar"
        ;;
    *Token*)
        echo "5"
        ;;
    *"So Close"*)
        echo "5"
        ;;
    *)
        echo "foobar"
        ;;
esac
